#!/bin/bash
# This script was generated by `phi-4` via `llama.cpp` from a prompt.

# Set the process name to match
PROCESS_NAME="mediaanalysisd"

# Find all PIDs matching the process name
PIDS=$(pgrep -U $UID -f "$PROCESS_NAME")

# Iterate through the list of PIDs
for PID in $PIDS; do
    # Check if the PID is valid
    if [ -n "$PID" ]; then
        #echo "Stopping process with PID: $PID"
        # Stop the process
        kill -STOP "$PID"

        # Check if the process was stopped successfully
        if [ $? -eq 0 ]; then
            #echo "Renicing process with PID: $PID"
            # Renice the process
            renice 20 "$PID"
        else
            echo "Failed to stop process with PID: $PID"
        fi
    else
        echo "No valid PID found for process name: $PROCESS_NAME"
    fi
done

